using NexusOps.Web.Models;
using Npgsql;
namespace NexusOps.Web.Services;
public interface ITeamStore { IReadOnlyList<TeamMember> ListToday(); void UpdateStatus(Guid employeeId, string status, string? location, string? task, bool doNotDisturb, string? actor); }
public sealed class PostgresTeamStore(NpgsqlDataSource dataSource, Guid tenantId) : ITeamStore
{
 public IReadOnlyList<TeamMember> ListToday() { const string sql="select e.id,coalesce(e.full_name,concat(e.first_name,' ',e.last_name)),coalesce(e.job_title,''),coalesce(p.presence_status,'off_duty'),p.work_location,p.current_task,coalesce(p.do_not_disturb,false),p.status_started_at,coalesce(w.work_mode,'clocked'),(select t.started_at from employee_time_entries t where t.employee_id=e.id and t.ended_at is null order by t.started_at desc limit 1) from employees e left join employee_presence p on p.employee_id=e.id left join employee_work_policies w on w.employee_id=e.id where e.tenant_id=$1 order by 2"; using var c=dataSource.CreateCommand(sql);c.Parameters.AddWithValue(tenantId);using var r=c.ExecuteReader();var list=new List<TeamMember>();while(r.Read())list.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.GetBoolean(6),r.IsDBNull(7)?null:r.GetFieldValue<DateTimeOffset>(7),r.GetString(8),r.IsDBNull(9)?null:r.GetFieldValue<DateTimeOffset>(9)));return list; }
 public void UpdateStatus(Guid id,string status,string? location,string? task,bool dnd,string? actor) { using var c=dataSource.CreateCommand("insert into employee_presence (tenant_id,employee_id,presence_status,work_location,current_task,do_not_disturb,status_started_at,updated_by_name) values ($1,$2,$3,$4,$5,$6,now(),$7) on conflict (employee_id) do update set presence_status=excluded.presence_status,work_location=excluded.work_location,current_task=excluded.current_task,do_not_disturb=excluded.do_not_disturb,status_started_at=now(),updated_by_name=excluded.updated_by_name,updated_at=now()");c.Parameters.AddWithValue(tenantId);c.Parameters.AddWithValue(id);c.Parameters.AddWithValue(status);c.Parameters.AddWithValue((object?)location??DBNull.Value);c.Parameters.AddWithValue((object?)task??DBNull.Value);c.Parameters.AddWithValue(dnd);c.Parameters.AddWithValue((object?)actor??DBNull.Value);c.ExecuteNonQuery(); }
}
public sealed class InMemoryTeamStore : ITeamStore { private readonly List<TeamMember> list=[new(Guid.NewGuid(),"Ivana Kovačević","Direktorica","focused","Zagreb","Pregled ponude",true,DateTimeOffset.UtcNow,"trust",null),new(Guid.NewGuid(),"Luka Marić","Voditelj održavanja","on_site","Pogon A","Dijagnostika CNC-a",false,DateTimeOffset.UtcNow,"clocked",DateTimeOffset.UtcNow.AddHours(-2))]; public IReadOnlyList<TeamMember> ListToday()=>list; public void UpdateStatus(Guid id,string s,string? l,string? t,bool d,string? a){var m=list.First(x=>x.EmployeeId==id);list[list.IndexOf(m)]=m with{Status=s,Location=l,Task=t,DoNotDisturb=d,StartedAt=DateTimeOffset.UtcNow};}}
